source 'https://github.com/GE-GAO-ZHAO/TALComponentTest-Spec.git'

use_frameworks!

platform :ios, '10.0'

target 'TestPodSourceLayered_Example' do
  pod 'TestPodSourceLayered', :path => '../'

  target 'TestPodSourceLayered_Tests' do
    inherit! :search_paths

    
  end
end
