use_frameworks!

platform :ios, '8.0'

target 'TestPodSourceLayered_Example' do
  pod 'TestPodSourceLayered', :path => '../'

  target 'TestPodSourceLayered_Tests' do
    inherit! :search_paths

    
  end
end
